server:
  port: 4014
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useSSL=false
    username: root
    password: root
    tomcat:
      max-active: 3
      max-idle: 1
      max-age: 5000
      max-wait: 3000
      min-idle: 1
  jpa:
    database-platform: mysql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
#If you configure multipart parameters then no need to configure CommonsMultipartResolver
  servlet:
    multipart:
      max-file-size: 5368709120KB
      location: /tmp
      max-request-size: 5368709120KB
  freemarker:
    template-loader-path:
    - classpath:/templates
    - WEB-INF/templates
    suffix: .ftl
    
    
    
    
    
    
    
    
    
    
    